language: python
jobs:
  include:
    - name: "Python 3.11.3 on Xenial Linux"
      python: 3.11.3
    - name: "Python 3.11.3 on macOS"
      os: osx
      osx_image: xcode12.2
      language: shell

before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt

script: python main.py || python3 main.py